spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db1
    username: pgdev
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev: update. Prod: validate or use Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: change-me-to-strong-secret
    expiration-ms: 3600000
